# This file is generated by ./Setup.py
class LocalConfig:

    @staticmethod
    def initialized():
        pass

    @staticmethod
    def get_db_name():
        return 'universe_db'

    @staticmethod
    def get_db_user():
        return 'postgres'

    @staticmethod
    def get_db_host():
        return '127.0.0.1'

    @staticmethod
    def get_db_port():
        return '5432'

    @staticmethod
    def get_db_password():
        return 'not_this_time'

    @staticmethod
    def get_workers_count():
        return 12

    @staticmethod
    def get_star_ratio():
        return 0.05
